### ISSUE TITLE
Getting Token Information vscode Error

### ISSUE THREAD

**Issue by markusheinemann** [auth0-samples/auth0-golang-api-samples#52]
I have struggled for some hours with a wired error when trying to access the token data. I use the code snippet from this example.

```
token := r.Context().Value(jwtmiddleware.ContextKey{}).(*validator.ValidatedClaims)
```

If the code is executed everything works as excepted. But the compiler of my editor (vscode) complains about an error. 

![image](https://user-images.githubusercontent.com/21105441/162094482-c7bed9d3-20c4-4595-9d98-e006ade002a6.png)

Is this anything related to the library/example or is this a bug in the editor?

**Comment by sergiught** [comment]
Hey @markusheinemann, apologies for the late reply on this one, the code from your screenshot is actually correct. I can't see anything wrong with it. I'm suspecting an issue with how the imports are loaded and indexed in VSCode. Especially considering that your code executes normally. If there would have been any issues it wouldn't have compiled. Because of this I'm closing this down.
